apiVersion: v1
kind: Pod
metadata:
  name: picket-pod
  labels:
    app: picket-pod
spec:
  containers:
    - name: picket
      image: tuannguyensn2001/picket
      envFrom:
        - configMapRef:
            name: config-picket